// <auto-generated />
using System;
using AdoptionApplication.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdoptionApplication.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdoptionApplication.Shared.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AdoptionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("HealthStatus")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<bool?>("IsAdopted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .HasColumnType("text");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Animal", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Kraków",
                            DateOfBirth = new DateTime(2018, 12, 31, 23, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Description = "Bazylka to urocza króliczka o pięknej, jasnorudej sierści. Ma duże, brązowe oczy i długie, puszyste uszy, które ciągle kręcą się na boki,słysząc każdy dźwięk w otoczeniu.Charakter Bazylki jest bardzo energiczny i zwinny. Lubi skakać, biegać i bawić się na świeżym powietrzu. Jest bardzoruchliwa i szybka, dzięki czemu unika niebezpieczeństw i łatwo przemieszcza się po swoim terenie.Bazylka jest także bardzo ciekawska i lubi odkrywać nowe rzeczy. Często chodzi po nowych miejscach,grzebie w ziemi i przekopywa nowe tunele. Lubi też poznawać nowych ludzi i zwierzęta, zachęcającdo zabawy swoim wesołym podejściem i chęcią do zabawy.Króliczka ta jest także bardzo uparta iczasem trudno zmusić ją do zrobienia czegoś, czego nie chce.Jednakże jest też bardzo kochana iprzyjacielska, zwłaszcza wobec swoich opiekunów. Lubi pieszczoty i przytulanie, a czasem sama uciekado ciepłego kąta, aby odpocząć i zrelaksować się.Ogólnie rzecz biorąc, Bazylka to urocza, pełna energiii wesoła króliczka o pięknej, jasnorudej sierści. Jej ruchliwość i zwinność sprawiają, że jest doskonałymtowarzyszem zabaw, a jej przyjacielskie nastawienie przyciąga do niej wiele nowych znajomości.",
                            Gender = "Samica",
                            HealthStatus = "Chory",
                            Image = "https://iili.io/HGRJuG1.jpg",
                            IsAdopted = false,
                            Name = "Bazylka",
                            Province = "Małopolskie",
                            ShortDescription = "Śmieszna wiewiórka, lubi jeść",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 2,
                            City = "Kraków",
                            DateOfBirth = new DateTime(2019, 3, 4, 23, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Description = "Chlebusz to uroczy królik o miękkim i puszystym, szarym futrze. Ma duże, czarne oczy i długie, uszate uszy, które ciągle kręcą się na boki, słysząc każdy dźwięk w otoczeniu.Charakter Chlebusza jest bardzo przyjacielski i łagodny. Lubi spędzać czas na wypoczynku, leżąc wygodnie na miękkiej poduszce lub grzebiąc w swojej ulubionej zielonej trawie. Jest bardzo łagodny i nieśmiały, ale też ciekawy świata i lubi poznawać nowych ludzi i zwierzęta.Chlebusz jest bardzo aktywny w ciągu dnia, lubi biegać po łące i skakać z jednego miejsca na drugie. Czasami jest też nieco roztrzepany i zapomina o swoich zadaniach, ale zawsze stara się naprawić swoje błędy.Królik ten lubi też dobrą, soczystą marchewkę oraz inne smaczne warzywa, które lubi zjadać podczas swoich przekąsek. Jest bardzo przywiązany do swojej rodziny i lubi spędzać czas z nimi, a także lubi przesypiać większą część dnia.Ogólnie rzecz biorąc, Chlebusz to uroczy, przyjacielski i aktywny królik, który kocha spędzać czas na wypoczynku, ale też chętnie poznaje nowych przyjaciół.",
                            Gender = "Samiec",
                            HealthStatus = "Zdrowy",
                            Image = "https://iili.io/HGRJA6F.jpg",
                            IsAdopted = false,
                            Name = "Chlebusz",
                            Province = "Małopolskie",
                            ShortDescription = "Królik nie z tego świata",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 3,
                            City = "Wrocław",
                            DateOfBirth = new DateTime(2020, 2, 9, 23, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Description = "Bamboszek to biały shih tzu o przyjaznym charakterze. Ma krótkie futerko, które jest miękkie w dotyku i wymaga regularnej pielęgnacji. Jego małe, czarne oczy emanują ciepłem i życzliwością, co sprawia, że trudno mu się oprzeć.Bamboszek jest bardzo energiczny i uwielbia bawić się ze swoim właścicielem. Jest to piesek inteligentny, który szybko się uczy i z łatwością zapamiętuje komendy. Lubi też biegać, skakać i bawić się zabawkami, a jego radosny temperament sprawia, że potrafi rozśmieszać każdego.Jest też bardzo przyjacielski i lojalny. Lubi być w bliskim kontakcie ze swoim właścicielem i często chętnie siada na kolanach lub przytula się do niego. Jest też bardzo czuły i wrażliwy, co sprawia, że łatwo go rozpieszczać i dawać mu wiele radości.Podsumowując, Bamboszek to uroczy shih tzu, który jest idealnym towarzyszem dla osób, które cenią sobie energię, inteligencję i lojalność w swoim psie. Jego radosny temperament i przyjacielski charakter sprawiają, że zawsze jest on gotowy do zabawy i pełen życzliwości w stosunku do swojego właściciela.",
                            Gender = "Samiec",
                            HealthStatus = "Zdrowy",
                            Image = "https://iili.io/HGAVrG4.jpg",
                            IsAdopted = false,
                            Name = "Bamboszek",
                            Province = "Dolnośląskie",
                            ShortDescription = "Mięciutki Bamboszek szuka domu",
                            SpeciesId = 2
                        });
                });

            modelBuilder.Entity("AdoptionApplication.Shared.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<bool?>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Species", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deleted = false,
                            Icon = "fa-solid fa-carrot",
                            Name = "Króliki",
                            Url = "rabbits"
                        },
                        new
                        {
                            Id = 2,
                            Deleted = false,
                            Icon = "fas fa-dog",
                            Name = "Psy",
                            Url = "dogs"
                        },
                        new
                        {
                            Id = 3,
                            Deleted = false,
                            Icon = "fas fa-cat",
                            Name = "Koty",
                            Url = "cats"
                        });
                });

            modelBuilder.Entity("AdoptionApplication.Shared.Animal", b =>
                {
                    b.HasOne("AdoptionApplication.Shared.Species", "Species")
                        .WithMany("Animals")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Animal_SpeciesId_fkey");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("AdoptionApplication.Shared.Species", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
